# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: trusty
sudo: required
os:
  - osx
  - linux
julia:
  - nightly
notifications:
  email: false
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia deps/build_pytensorflow.jl
    - julia -e 'Pkg.build("TensorFlow")'
    - julia -e 'Pkg.test("TensorFlow")'
