# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: trusy
sudo: required
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("TensorFlow")'
    - julia -e 'Pkg.test("TensorFlow")'
